@startuml
top to bottom direction

interface IWeatherService<T> <<where T : WeatherData>>
{
    +FetchWeather(LocationData location) : T
}
interface IDataProvider << (I,orchid) Strategy >> 
{
    +GetWeather(location, type) : WeatherData
}
interface IWeatherObserver
{
    + void Update(WeatherData data)
}

interface ISubject 
{
    + Attach 
    + Detach
    + Notify
}

class WatchedLocation
{
    - _city : string
    + observers[]
    + UpdateWeather(WeatherData data)
}

WatchedLocation --|> ISubject : implements

class APIClient << (C,orchid) Singleton >>
{
+ http : var
+ dynamicURL : string
+ response : var
+ content : var
}

together {
    abstract class WeatherData
    class CurrentWeatherData
    {
        + time : string
        + temperature_2m : double
        + rain : double
        + snowfall : double
        + apparent_temperature : double
        + cloud_cover : double
    }
    class HourlyWeatherData
    {
        + time : string[]
        + temperature_2m : double[]
        + rain : double[]
        + snowfall : double[]
        + apparent_temperature : double[]
        + cloud_cover : double[]
    }
    class DailyWeatherData 
    {
        + time : string[]
        + temperature_2m_max : double[]
        + temperature_2m_min : double[]
        + rain_sum : double[]
        + snowfall_sum : double[]
        + wind_speed_10m_max : double[]
    }
    class HistoricalWeatherData
    {
    }
    
    DailyWeatherData -up-|> WeatherData : inherits
    HourlyWeatherData -up-|> WeatherData : inherits
    CurrentWeatherData -up-|> WeatherData : inherits
    HistoricalWeatherData -up-|> DailyWeatherData : inherits
}

class LocationData
{
    + laltitude : double
    + longtitude : double
}
class GeolocationService
{
    +GetCoordinates(city) : LocationData
}

GeolocationService -up-> APIClient : uses

together {
    class CurrentWeatherService
    {
        + provider : IDataProvider
        +FetchWeather(location : LocationData) : CurrentWeatherData
    }
    
    class DailyWeatherService
    {
        + provider : IDataProvider
        +FetchWeather(location : LocationData) : DailyWeatherData
    }
    
    class HourlyWeatherService
    {
        + provider : IDataProvider
        +FetchWeather(location : LocationData) : HourlyWeatherData
    }
    
    class HistoricalWeatherService
    {
        + provider : IDataProvider
        +FetchWeather(location : LocationData) : HistoricalWeatherData
    }
    
    DailyWeatherService -up-|> IWeatherService : implements
    HourlyWeatherService -up-|> IWeatherService : implements
    CurrentWeatherService -up-|> IWeatherService : implements
    HistoricalWeatherService -up-|> IWeatherService : implements
    IWeatherService ..> IDataProvider

}

enum WeatherServiceType
{
    + currentWeather
    + dailyWeather
    + hourlyWeather
    + historicalWeather
}

class WeatherServiceFactory << (C,orchid) Factory >>
{
    +CreateWeatherService<T>(type : WeatherServiceType) : IWeatherService<T>
}

WeatherServiceFactory -up-> CurrentWeatherService : creates 
WeatherServiceFactory -up-> DailyWeatherService : creates 
WeatherServiceFactory -up-> HourlyWeatherService : creates 
WeatherServiceFactory -up-> HistoricalWeatherService : creates

together {
    class APIDataProvider
    {
        + client : APIClient
        + GetWeather(location, type)
        + BuildUrl(location, type)
    }
    
    class HistoryDataProvider
    {
        + apiFallback : APIDataProvider
        + history : CachedWeatherHistory
        + HistoryDataProvider() 
        + GetWeather(location, type)
    }
    
    APIDataProvider -up-|> IDataProvider
    HistoryDataProvider -up-|> IDataProvider
    APIDataProvider -up-> APIClient : uses
    HistoryDataProvider -down-> CachedWeatherHistory
    HistoryDataProvider -up-> APIDataProvider : fallback

}

class WeatherHistoryMemento << (C,orchid) Memento >> {
    +data : WeatherData
    +timestamp : DateTime
}

class CachedWeatherHistory
{
    - history : List<WeatherHistoryMemento>
    + SaveState(data)
    + GetLast() :  WeatherHistoryMemento
}

CachedWeatherHistory --> WeatherHistoryMemento : keeps

together {
    class TemperatureAlert
    {
    - _city : string
    - _temperatureThreshold : double
    + TemperatureAlert(string city, double threshold)
    + void Update(WeatherData data)
    }
    class ThunderstormAlert
    {
    - _city : string
    - _thunderstormPresence : bool
    + ThunderstormAlert(string city, bool presence)
    + void Update(WeatherData data)
    }
    class FloodAlert
    {
    - _city : string
    - _flood : double
    + FloodAlert(string city, double flood)
    + void Update(WeatherData data)
    }
    
    TemperatureAlert -up-|> IWeatherObserver 
    ThunderstormAlert -up-|> IWeatherObserver
    FloodAlert -up-|> IWeatherObserver

}

class WeatherReport 
{
    + title : string
    + content : string
}

interface IWeatherReportBuilder << (I,orchid) Builder >>
{
    + AddSummary()
    + AddMinMax()
    + AddTrends()
    + AddTemperatureThresholdDay()
    + GetResult() : WeatherReport
}



@enduml