@startuml
top to bottom direction

enum ReportType
{
    CURRENT_CONDITIONS
    WEEKLY_FORECAST
    HOURLY_FORECAST
    HISTORICAL_ANALYSIS
    LOCATION_COMPARISON
}

enum WeatherServiceType
{
    CURRENT
    DAILY_7
    HOURLY_24
    HISTORICAL
}

interface IWeatherService 
{
    +FetchWeather(LocationData) : Task<WeatherData>
}
interface IDataProvider << (I,orchid) Strategy >> 
{
    +GetWeatherData(LocationData location, WeatherServiceType serviceType) : Task<WeatherData>
}

together {
    class APIDataProvider
    {
        - _client : APIClient
        + APIDataProvider()
        + GetWeatherData(LocationData location, WeatherServiceType serviceType) : Task<WeatherData>
        + BuildUrl((LocationData location, WeatherServiceType serviceType) : string
    }
    
    class CachedDataProvider
    {
        - _cache : CachedWeatherHistory 
        - _fallbackProvider : IDataProvider
        - _cacheValidityMinutes : int
        + CachedDataProvider(IDataProvider fallbackProvider, int cacheValidityMinutes)
        + GetWeatherData(LocationData location, WeatherServiceType serviceType) : Task<WeatherData>
    }
    
    APIDataProvider -up-|> IDataProvider
    CachedDataProvider -up-|> IDataProvider
    APIDataProvider -up-> APIClient : uses
    CachedDataProvider -down-> CachedWeatherHistory
    CachedDataProvider -up-> APIDataProvider : fallback

}

class APIClient << (C,orchid) Singleton >>
{
    - _instance : APIClient
    - _httpClient : HttpClient
    - APIClient()
    + GetInstance() : APIClient
    + GetAsync<T>(string url) : Task<T>
    
}

class GeolocationService
{
    - _client : APIClient
    + GeolocationService()
    + GetLocation(string cityName) : Task<LocationData>
}

GeolocationService -up-> APIClient : uses


together {
    abstract class WeatherData
    {
        + latitude : double
        + longitude : double
        + timezone : string
        
        + GetLocation() : LocationData
        + GetSummary() : string
    }
    class CurrentWeatherData
    {
        + time : string
        + temperature_2m : double
        + rain : double
        + snowfall : double
        + apparent_temperature : double
        + cloud_cover : double
        + wind_speed_10m : double
        + weather_code : int
        
        + GetSummary() : string
    }
    
    class CurrentWeatherResponse
    {
        + latitude : double
        + longitude : double
        + timezone : string
        + current : CurrentWeatherData
    }
    
    class HourlyWeatherData
    {
        + time : string[]
        + temperature_2m : double[]
        + rain : double[]
        + snowfall : double[]
        + cloud_cover : double[]
        + wind_speed_10m : double[]
        + weather_code : int[]
                
        + GetSummary() : string
    }
    
    class HourlyWeatherResponse
    {
            + latitude : double
            + longitude : double
            + timezone : string
            + hourly : HourlyWeatherData
    }
    
    class DailyWeatherData 
    {
        + time : string[]
        + temperature_2m_max : double[]
        + temperature_2m_min : double[]
        + rain_sum : double[]
        + snowfall_sum : double[]
        + wind_speed_10m_max : double[]
        
        + GetSummary() : string
    }
    
     class DailyWeatherResponse
    {
        + latitude : double
        + longitude : double
        + timezone : string
        + daily : DailyWeatherData
    }
    
    class HistoricalWeatherData
    {
        + start_date : string[]
        + end_date : string[]
        + daily : DailyWeatherData
        + HistoricalWeatherData()
        + GetSummary() : string
    }
    
     class HistoricalWeatherResponse
    {
        + latitude : double
        + longitude : double
        + timezone : string
        + daily : DailyWeatherData
    }
    
    DailyWeatherData -up-|> WeatherData : inherits
    HourlyWeatherData -up-|> WeatherData : inherits
    CurrentWeatherData -up-|> WeatherData : inherits
    HistoricalWeatherData -up-|> DailyWeatherData : inherits
}

class LocationData
{
    + laltitude : double
    + longtitude : double
    + LocationData(double lat, double lon) : LocationData
}

class GeocodingResponse
{
    + results : List<LocationData>?
}

together {
    class CurrentWeatherService
    {
        - _provider : IDataProvider
        + CurrentWeatherService(IDataProvider provider)
        +FetchWeather(LocationData location) : Task<WeatherData>
    }
    
    class DailyWeatherService
    {
        - _provider : IDataProvider
        + DailyWeatherService(IDataProvider provider)
        +FetchWeather(LocationData location) : Task<WeatherData>
    }
    
    class HourlyWeatherService
    {
       - _provider : IDataProvider
        + HourlyWeatherService(IDataProvider provider)
        +FetchWeather(LocationData location) : Task<WeatherData>
    }
    
    class HistoricalWeatherService
    {
        - _provider : IDataProvider
        + HistoricalWeatherService(IDataProvider provider)
        +FetchWeather(LocationData location) : Task<WeatherData>
    }
    
    DailyWeatherService -up-|> IWeatherService : implements
    HourlyWeatherService -up-|> IWeatherService : implements
    CurrentWeatherService -up-|> IWeatherService : implements
    HistoricalWeatherService -up-|> IWeatherService : implements
    DailyWeatherService ..> IDataProvider : uses
    HourlyWeatherService ..> IDataProvider : uses
    CurrentWeatherService ..> IDataProvider : uses
    HistoricalWeatherService ..> IDataProvider : uses
}

class WeatherServiceFactory << (C,orchid) Factory >>
{
    - _provider : IDataProvider
    + WeatherServiceFactory(IDataProvider provider)
    +CreateWeatherService(WeatherServiceType type) : IWeatherService
}

WeatherServiceFactory -up-> CurrentWeatherService : creates 
WeatherServiceFactory -up-> DailyWeatherService : creates 
WeatherServiceFactory -up-> HourlyWeatherService : creates 
WeatherServiceFactory -up-> HistoricalWeatherService : creates


class WeatherHistoryMemento << (C,orchid) Memento >> {
    +Data : WeatherData
    +Timestamp : DateTime
    +Location : LocationData
    + WeatherHistoryMemento(WeatherData data, LocationData location)
}

class CachedWeatherHistory
{
    - _history : Dictionary<string, List<WeatherHistoryMemento>>
    + CachedWeatherHistory()
    + SaveState(WeatherData data, LocationData location, WeatherServiceType serviceType) : void
    + GetLast(LocationData location, WeatherServiceType serviceType) : WeatherHistoryMemento
    + GetLocationKey(LocationData location, WeatherServiceType serviceType) : string
    + CleanOldData(string key) : void
}

CachedWeatherHistory --> WeatherHistoryMemento : keeps

together {
    class TemperatureAlert
    {
    - _city : string
    - _temperatureThreshold : double
    + TemperatureAlert(string city, double threshold)
    + void Update(WeatherData data)
    }
    class ThunderstormAlert
    {
    - _city : string
    - _thunderstormPresence : bool
    + ThunderstormAlert(string city, bool presence)
    + void Update(WeatherData data)
    }
    class FloodAlert
    {
    - _city : string
    - _flood : double
    + FloodAlert(string city, double flood)
    + void Update(WeatherData data)
    }
    
    TemperatureAlert -up-|> IWeatherObserver 
    ThunderstormAlert -up-|> IWeatherObserver
    FloodAlert -up-|> IWeatherObserver

}

interface IWeatherObserver << (C,orchid) Observer >>
{
    + Update(WeatherData data) : void
}

interface ISubject
{
    + Attach(IWeatherObserver observer) : void
    + Detach(IWeatherObserver observer) : void
    +Notify() : void
}

class WatchedLocation
{
    + _locationData : LocationData
    - _observers : List<IWeatherObserver>
    - _currentWeather : CurrentWeatherData
    - _forecast : DailyWeatherData
    + WatchedLocation(LocationData location)
    +Attach(IWeatherObserver observer) : void
    +Detach(IWeatherObserver observer) : void
    +Notify() : void
    + UpdateWeather(CurrentWeatherData current, DailyWeatherData forecast = null)
}


@enduml